### ISSUE TITLE
Failed to load the UI

### ISSUE THREAD

**Issue by petprog** [smilecs/rick_morty_api_sample#4]
After successful builds and installation of the app. The UI is blank but It shows on the Logcat that the data loaded from the api successfully.

I have checked internet connectivity - Good

**Comment by smilecs** [comment]
> After successful builds and installation of the app. The UI is blank but It shows on the Logcat that the data loaded from the api successfully.
> 
> I have checked internet connectivity - Good

Hello, I would have a look at this and send a pull request soon
